name: customElementDemo
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: Jenny Messerly <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  js: ^0.6.0
  meta: ^1.1.0
  html5:
    git: https://github.com/jifalops/html5

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
